version: "3.8"

services:
  # --- Infrastructure Services ---

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

  # --- Application Services ---

  api:
    container_name: api-service
    build:
      context: ./packages/api
    ports:
      - "3000:3000"
    env_file:
      - ./packages/api/.env
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - app-network

  worker:
    container_name: worker-service
    build:
      context: ./packages/worker
    env_file:
      - ./packages/worker/.env
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - app-network

  generator:
    container_name: generator-service
    build:
      context: ./packages/generator
    env_file:
      - ./packages/generator/.env
    depends_on:
      - api
    networks:
      - app-network

  frontend:
    container_name: frontend-service
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - app-network

# --- Volumes and Networks ---

volumes:
  elasticsearch-data:
  rabbitmq-data:

networks:
  app-network:
    driver: bridge
